wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    code_path: code/scripts/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1668687855.819869
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 3
      - 16
      - 23
      4: 3.9.12
      5: 0.13.3
      8:
      - 5
activation_fn:
  desc: null
  value: ReLU()
batch_size:
  desc: null
  value: 64
conv_layers:
  desc: null
  value:
  - 1
  - 4
  - 8
device:
  desc: null
  value: cuda
early_stopping:
  desc: null
  value: true
epochs:
  desc: null
  value: 100
kernel_size:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.001
load_model:
  desc: null
  value: false
loss_fn:
  desc: null
  value: MultiLabelSoftMarginLoss()
wandb:
  desc: null
  value: true
